name: catculator
description: "2024 capstone project"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.1.0
  cloud_firestore: ^5.3.0
  firebase_storage: ^12.3.4
  image_picker: ^1.0.0


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  assets:
    - assets/


  uses-material-design: true

