name: catculator
description: "2024 capstone project"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.1.0
  mailer: ^6.0.0
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  image_picker: ^1.1.2
  uni_links5: ^0.5.4
  qr_flutter: ^4.1.0
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1


  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  uuid: ^4.5.1
  mixpanel_flutter: ^2.3.3
  mobile_scanner: ^6.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/


  uses-material-design: true

