// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5eEOA70IU2ol8R47pU0g_KHaAy3JWEMI',
    appId: '1:408587343572:web:0b222c29e889de64360d41',
    messagingSenderId: '408587343572',
    projectId: 'capstone-team4',
    authDomain: 'capstone-team4.firebaseapp.com',
    storageBucket: 'capstone-team4.appspot.com',
    measurementId: 'G-MDZD38EJJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_kWlYLSRT7W0rJHUttPWKpR3_0DaYTHE',
    appId: '1:408587343572:android:e78b49f7e5b7de7b360d41',
    messagingSenderId: '408587343572',
    projectId: 'capstone-team4',
    storageBucket: 'capstone-team4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCztURxmv_2nENm4xfeOMQ6wMxKIgm72wA',
    appId: '1:408587343572:ios:f05af2ba114f6bda360d41',
    messagingSenderId: '408587343572',
    projectId: 'capstone-team4',
    storageBucket: 'capstone-team4.appspot.com',
    iosBundleId: 'com.clk.team4.catculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCztURxmv_2nENm4xfeOMQ6wMxKIgm72wA',
    appId: '1:408587343572:ios:f05af2ba114f6bda360d41',
    messagingSenderId: '408587343572',
    projectId: 'capstone-team4',
    storageBucket: 'capstone-team4.appspot.com',
    iosBundleId: 'com.clk.team4.catculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5eEOA70IU2ol8R47pU0g_KHaAy3JWEMI',
    appId: '1:408587343572:web:e62929cd2cc9175e360d41',
    messagingSenderId: '408587343572',
    projectId: 'capstone-team4',
    authDomain: 'capstone-team4.firebaseapp.com',
    storageBucket: 'capstone-team4.appspot.com',
    measurementId: 'G-FHW8WKE3LP',
  );

}